[tool.pyright]

# https://github.com/microsoft/pyright/blob/main/docs/configuration.md

exclude = [
    "**/__pycache__/**",
    "**/_Archives/**",
    "*.py",
    "Test/**",
    "Sources/**",
    "XLSX/**",

]

extraPaths = [
    "/usr/local/anaconda3/envs/DBLP/lib/python3.10/",
    "/usr/local/anaconda3/envs/DBLP/lib/python3.10/site-packages"  
]

pythonVersion = "3.10"
pythonPlatform = "Darwin"